name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python*/site-packages
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github/workflows/lint.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-${{ hashFiles('**/pyproject.toml') }}-
          ${{ runner.os }}-pip-lint-

    - name: Configure pip for network resilience
      run: |
        # Create pip config for better network handling
        mkdir -p ~/.pip
        cat > ~/.pip/pip.conf << 'EOF'
        [global]
        timeout = 300
        retries = 3
        default-timeout = 300
        EOF

    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --timeout 300 --retries 3 black flake8 mypy numpy

    - name: Lint with black
      run: |
        black --check --diff src/ tests/
      timeout-minutes: 5

    - name: Lint with flake8
      run: |
        flake8 src/ tests/
      timeout-minutes: 5

    - name: Type check with mypy
      run: |
        mypy src/python_gpr/__init__.py src/python_gpr/conversion.py src/python_gpr/core.py src/python_gpr/metadata.py
      timeout-minutes: 10